# Jekyll configuration for GitHub Pages
title: Pedro Benicio's Portfolio
description: A collection of web development projects and experiments

# Exclude node_modules and other build artifacts from Jekyll processing
exclude:
  - node_modules/
  - "projects/*/node_modules/"
  - "projects/*/node_modules/**/*"
  - "projects/*/dist/"
  - "projects/**/package.json"
  - "projects/**/package-lock.json"
  - "projects/**/*.config.js"
  - "projects/**/*.config.ts"
  - "projects/**/tsconfig.json"
  - "projects/**/yarn.lock"
  - "projects/**/README.md"
  - "projects/**/*.md"
  - vendor/
  - Gemfile
  - Gemfile.lock

# GitHub Pages settings
plugins:
  - jekyll-relative-links

# Markdown settings
markdown: kramdown
highlighter: rouge

# Site settings
baseurl: ""
url: "https://hilbertsguest.github.io"

# Build settings
safe: true
incremental: false